import React from 'react'

export default React.createClass({
	render(){
		return(
			<div>
			<h2>Combining Qualitative and Time Series Forecasting to Increase the Forecasting Accuracy for Instant Noodle Sales in Thailand</h2>
<h3>ABSTRACT</h3>

<p>Demand forecasting is very important for the planning process. The forecast accuracy affects the efficiency of the procurement, production and delivery processes. Our research has the objective of increasing the sales forecasting accuracy of instant noodles for a case study company in Thailand. Many factors affect the sales of instant noodles, such as promotion, other commodities’ prices, national disaster and production capacity. Thus, we collected historical monthly sales data, analysed the data and their pattern and considered whether the data were irregular due to those factors. After obtaining the forecast data, data intervention by adjustment of the irregular effects was performed in accordance with our experience and judgement. Next, we used the predictor function in the Crystal Ball software to determine the best time series forecasting method for actual and adjusted sales data. Then, we verified the result with the actual sales data for one year. The result showed that the adjustment could increase the sales forecast accuracy by 46.14%, 22.53% and 56.42% for products A, B and C, respectively. In summary, the mean average percentage sales forecast error after adjustment was 6.48%–11.62%, which is better than the current method of forecasting based on experts.</p>

<h3>1. INTRODUCTION</h3>

<p>Demand forecasting is a major issue for every company, especially in the food industry, in which most products are fast moving and substitutable. Therefore, demand forecasting is very important in a competitive industry. To increase the sales forecasting accuracy, the factors influencing the sales must be explored, such as using historical sales data to analyse the composition of sales. Then, it is necessary to check which external factors affected the sales, such as policy changes, price changes in raw material and other commodities, strikes, promotions and natural disasters. Hence, several factors can affect sales, such as historical sales, pricing strategies, competitor prices, advertising, promotion, trends and seasonality (Leone, 1987; Divakar et al., 2005). The intervention analysis studied the impact of extraordinary external events on forecasting, such as policy changes, strikes, promotions and natural disasters (Montgomery and Weatherby, 1980). The research on qualitative forecasting by expert judgement and the quantitative forecasting method was explored. The study of human intervention in the sales forecast of 281 products showed that the forecast accuracy after intervention increased (Mathews and Diamantopoulos, 1986). In addition, the forecast including intervention proved to be better than the forecast without intervention (Goh and Law, 2002). The case study company is one of the leading instant noodle manufacturers in Thailand (Khamphinit, 2014). Forecasting accuracy is one of the goals of the company for efficient procurement, production planning and inventory control. The sales of instant noodles were mainly from retailers, such as modern traders, which are usually affected by sales promotion and price changes. We studied the historical sales data, which covered the national disaster in Thailand in 2011 that led to a dramatic increase in sales. We combined the qualitative and quantitative forecasting models including intervention by sales data adjustment to improve the forecasting accuracy.</p>

<h3>2. METHODOLOGY</h3>

<p>First, we collected the historical sales data of selected instant noodles for 48 months. Second, we separated the data into two groups: a test set composed of the first 36 months and a verified set composed of the 12 latest months. Then, we plotted a graph to analyse the pattern of the data and to check whether any factor distorted the demand, such as promotion, capacity expansion or national disaster. Later, we adjusted the actual sales data according to the demand distortion. For example, if the sales were too high due to promotion or national disaster, then we adjusted them by reducing them. On the other hand, if the actual sales were low due to low capacity, then we adjusted them by increasing the sales equal to the amount of capacity expansion. Note that we made this adjustment because the current situation is that the demand is greater than the supply. Hence, this implies that when a company expands its capacity, the sales will increase. On the other hand, we did not adjust the sales if the demand was less than the supply. Next, we determined the best time series method of actual and adjusted 36-month data and measured the forecast accuracy by mean absolute percentage error (MAPE), because this can be used to compare different products (Goh and Law, 2002). Then, the best forecasting method was determined by the predictor function in the Crystal software, which can report the best forecasting method. Finally, we compared the result of the actual and adjusted forecasts of a verified data set using MAPE.</p>

<h3>3. RESULTS</h3>

<h4>3.1. COMPARISON OF ACTUAL AND ADJUSTED SALES PATTERNS FOR INSTANT NOODLES</h4>

<p>We considered the total products of an instant noodle manufacturer (Khamphinit, 2014), consisting of several types of products. Hence, we selected three main products according to the ABC analysis. We selected the three fastest-moving products to study. First, we selected the historical sales data of products A, B and C from 2010 to 2013. Then, we plotted the monthly historical sales data from 2010 to 2012 from the test data. After that, we analysed the irregular events and adjusted the actual sales accordingly, as shown in Table 1. The analysis shows that, first, the company expanded its capacity in April 2010; hence, the actual sales used as an input for time series forecasting must be adjusted by a similar amount. Next, a huge flood occurred in October 2011 to December 2011. The sales during the flood were extremely high and these sales must be adjusted to remove this effect. In addition, some retailers over-stocked their inventories during the flood. Thus, the actual sales were reduced irregularly and we increased the sales accordingly. On the other hand, some suppliers were affected by the flood and raw materials could not be delivered. Hence, the sales decreased irregularly and an adjustment must be made for this as well. In addition, there were some promotions from time to time, which led to an increase in sales. Likewise, the promotion effect must be removed from the actual sales. In all, we adjusted all the irregular effects in the actual values, as shown in Table 1. Next, the comparison between the actual and the adjusted historical sales data of products A, B and C are shown in Figures 1–3.</p>

<h3>3.2. COMPARISON OF ACTUAL AND ADJUSTED FORECASTING METHODS FOR INSTANT NOODLE SALES FORECASTING</h3>

<p>The analysis of the data pattern before using the forecasting package helped us to understand the characteristics of the sales, such as trends and seasonality, and to determine whether there was any irregular pattern. We selected fast-moving products of instant noodles, which could be affected by several factors. We found that the sales of the three products had seasonality, but only product B followed a trend. The best time series forecasting method for products A, B and C using actual sales was double exponential smoothing, which implied that there was a trend only. The forecast errors of the three test data sets were 8.79%–12.15%, but those of the verified data were 12.68%–15.00%, which were higher. However, after adjusting the sales data, the forecast errors of the test data were 7.13%–7.21%, but those of the verified data were 6.48%–11.62%. Hence, the adjustment by experts could increase the forecast accuracy between 22.53%–56.42%, as shown in Table 2. Figure 4 shows that the forecasts of the adjusted sales data of all the products were closer to the actual sales data than the forecasts of the non-adjusted sales data. The coefficient variation (CV) of the sales of product B fluctuated more than those of A and C. This aligned with the result that the forecast of product B was less accurate.</p>

<p>In summary, the adjustment of sales data by experts who know the effect of past events on the historical sales could increase the forecast accuracy. For example, if there is a promotion, the sales will increase. Hence, the regular sales without promotion should be deduced from the past sales. Similarly, when other commodities’ prices increase or a national disaster such as a flood occurs, then the sales will increase. If we use these irregular sales data to forecast the future, when the same event may not occur, then the forecast error might be huge without data adjustment. On the other hand, if the production capacity is increased, then the sales in the past might not be a good representative to be used as historical data. Sales adjustment before forecasting to normalise the data outperforms. However, if similar events could occur in the future, the user can adjust the forecast data accordingly.</p>

<h3>4. CONCLUSION</h3>

<p>Sales forecasting accuracy is very important for planning processes such as procurement, production and delivery. This research studied how to improve sales forecasts by adjusting the sales pattern of instant noodles from a case study company in Thailand according to the events that occurred in the past, such as promotion, capacity expansion and floods. The result showed that using the adjusted sales data as the input data for forecasting following the time series method could increase the sales forecast accuracy by 46.14%, 22.53% and 56.42% for products A, B and C, respectively. Then, the verification showed that the mean average percentage sales forecast error after adjustment was 6.07%–11.62%, which is better than the current method, in which forecasting is based on experts without data intervention. In summary, the mixed forecasting method between qualitative forecasting by adjustment of sales data by experts and quantitative forecasting by time series using a software package could increase the forecast accuracy.</p>

<p>There are two major factors that drive the irregular sales. First, the factors from internal supply chain such as suppliers, company and its customers. Second, the factors from external supply chain such as the economy, society, natural disaster, government policy and regulation, etc. These are causes of bullwhip effect in the supply chain. Furthermore, the demand forecasting performed individually in the supply chain caused the bullwhip effect, which is the variance of order quantity to the variance of demand (Lee et al., 2004; Boute and Lambrecht, 2009; Barlas and Gunduz, 2011). Hence, the sharing of demand and forecast between suppliers and customers could help to reduce the bullwhip effect (Barlas and Gunduz, 2011). Time series forecasting methods have been used to forecast practical problems (Montgomery and Weatherby, 1980; Doganis et al., 2006). In the future, the sharing of POS information from retailers should be an option for further improvement of the forecast accuracy for the company.</p>

			
			</div>
		)
	}
})